### ISSUE TITLE
can't save content with tagdiv composer plugins (wp v4.7 and ionmag v1.3)

### ISSUE THREAD

**Issue by xhb** [tagDiv/ionMag#4]
i got two issues,   (wp v4.7 and ionmag v1.3)
1.  lost some css styles after installing ionmag default demos .
2.  get some error after a tdcJobManager.addJob callback.

console output:
tdcJobManager.addJob                 js_files_for_wp_admin.min.js:12 
 clear  _deletePanel                        js_files_for_wp_admin.min.js:12
 tdcJobManager.addJob - Error callback - textStatus: parsererror errorThrown: SyntaxError: Unexpected token < in JSON at position 0        js_files_for_wp_admin.min.js:12 
jobRequest
columns: 3 
jobId: 0 
postId: "429"
replyHtml: ""
shortcode: "[vc_empty_space]"
__proto__: Object                            js_files_for_wp_admin.min.js:12 
clear  _deletePanel

**Comment by opradu** [comment]
Hi,

sorry for the delay, please try to update to the latest version of our [free news theme](https://www.wpion.com/free-news-theme/)

also we have community support here: http://forum.wpion.com/forum/ionmag/

**Comment by bblurock** [comment]
Hi, I also encounter the similar issue, every time I try to save from tagDiv Editor.

I have the following error

> Failed to load resource: the server responded with a status of 404 (Not Found)

And the callback print out 
```
js_files_for_wp_admin.min.js:12 tdcJobManager.addJob - Error callback - textStatus: error errorThrown: Not Found
```
```
js_files_for_wp_admin.min.js:12 
  jobRequestc
    olumns: 3
    jobId: 0
    postId: "181"
    replyHtml: ""
    shortcode: "[td_block_4]"
    __proto__: Object
js_files_for_wrapper.min.js:20 tdcJobManager.addJob - ERROR: 404 not found
```

My env info:
```
    Wordpress: 4.7.2
    IonMag Version: 1.4 
    tagDiv Version: 1.0
```

**Comment by cristealucian** [comment]
Hi 

@xhb @bblurock 
The latest version of the ionMag theme (Version: 1.5.1 - Release date: 10.05.2017) should fix these matters so please update you theme and let us know if you still have issues and please also provide a link and contact our theme support forum: https://www.wpion.com/members/forum/ionmag/
