### ISSUE TITLE
Cron Schedule Issue

### ISSUE THREAD

**Issue by barans** [tagDiv/ionMag#5]
When you add cron schedules in td_cake.php file, you didn't take $schedules parameter in the function therefore you override every cron schedules in the system.

You can fix this issue by replacing the 549. line  	
function _schedule_modify_add_three_days($schedules) {

Thank you.

**Comment by cristealucian** [comment]
The fix for this and will be available in the next theme version.

Thank you form reporting this!

**Comment by angelcosta** [comment]
Thank you. I've been having problems with cron and had no idea the theme was to blame.
