### ISSUE TITLE
Incorrect sidebar box fixing

### ISSUE THREAD

**Issue by SchDen** [tagDiv/ionMag#8]
![screen shot 2017-06-17 at 16 15 45](https://user-images.githubusercontent.com/1484977/27253182-81069132-5378-11e7-8e71-6d8404cd3e26.png)
When the header is sticky, sidebar box have to incorrect position

**Comment by cristealucian** [comment]
> I cannot recreate the latest version of the theme (Version: 1.5.1 - Release date: 10.05.2017)
> I believe it works well now.
> If you still face this issue please let us know and address here:  https://www.wpion.com/members/forum/ionmag/
