### ISSUE TITLE
Polish characters in "raw html" do not appear

### ISSUE THREAD

**Issue by technologiegalwaniczne** [tagDiv/ionMag#9]
I am having some trouble when trying to add some text with polish letter like (ł,ó,ź etc.).
The letters do not appear like in picture below.

![image](https://user-images.githubusercontent.com/29600665/27690839-b2f0caa0-5ce2-11e7-8abe-04d8cd721c42.png)

Any ideas?
Best regards

**Comment by cristealucian** [comment]
Hi,

Yes, we will look into this and try to find a fix for it as soon as possible. 
Thanks for letting us know!

For any other future theme related issues please address to our theme support forum here: https://www.wpion.com/members/forum/ionmag/
